# This file is no longer actively used by the devcontainer, as
# Postgres is now running as a native service inside the container.
# This is kept for reference.

services:
#   db:
#     image: postgres:latest
#     container_name: postgres_db
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
