services:
  mysql:
    image: mysql
    container_name: cgvs_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cgvs_db
      MYSQL_USER: cgvs_user
      MYSQL_PASSWORD: cgvs_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cgvs_network

networks:
  cgvs_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
