schema:
  [
    "client/graphql/generated/schema.graphql",
  ]
documents: "**/**/*.graphql"
extensions:
  endpoints:
    default:
      url: http://localhost:3000/api/graphql
      headers:
        user-agent: JS GraphQL
