schema:
  [
    "graphql-generated/schema.graphql",
    "schema-directives.graphql",
    "programmatic-types.graphql",
  ]
documents: "**/**/*.graphql"
extensions:
  endpoints:
    default:
      url: http://localhost:8080/graphql
      headers:
        user-agent: JS GraphQL
