ktor:
  application:
    modules:
      - ApplicationKt.module
  deployment:
    port: 8080
postgres:
  url: "jdbc:postgresql://localhost:5432/postgres"
  user: postgres
  password: postgres
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
  secret: "your-super-secret-jwt-key-change-in-production"

filesystem:
  upload_limit: 2048

image:
  allowed_types: ['jpeg', 'png', 'jpg', 'gif']
